[package]
name = "burrito-lp-locker"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema = "1.5.8"
cosmwasm-std = "1.5.8"
cw-storage-plus = "1.2.0"
cw20 = "1.1.2"
schemars = "0.8.22"
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
thiserror = "1.0.69"
